### ISSUE TITLE
This file is too large error message

### ISSUE THREAD

**Issue by bmann** [pdelfan/ouranos#5]
![IMG_7276](https://github.com/user-attachments/assets/6caa66f5-6c36-4e02-a131-7ac84a4cce57)

I had multiple rich text links which I then deleted. Then I removed one image. 

Not sure where this error is from.

**Comment by pdelfan** [comment]
Hey @bmann this should be fixed now. The upper limit for image compression was set to 1MB [but it's practically 976.56KB](https://bsky.app/profile/pfrazee.com/post/3jvz7k4hj2d2c).

**Comment by bmann** [comment]
Nice! Working great, thank you!

**Comment by pdelfan** [comment]
> Nice! Working great, thank you!

Thanks for letting me know!
